"""
hugg_backend/main.py

FastAPI backend for Hugging Face KRA analysis.

This is a completely separate backend that:
  1. Reads patient data from the SAME workflow SQLite DB used by analysis_flow
  2. Reuses the FAISS retrieval context already generated by the local pipeline
  3. Builds the KRA prompt
  4. Sends it to a Hugging Face Space for inference
  5. Returns the result to the frontend popup

Port: 8090 (does NOT conflict with analysis_flow on 8080)
"""

from __future__ import annotations

import json
import logging
import os
import time
from typing import Any, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field

load_dotenv()

from db import get_session, get_retrieval_context
from hf_client import call_hf_space, get_hf_token
from prompt_builder import build_kra_prompt

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="HeartSense HF Analysis Backend",
    description="Hugging Face Space inference for KRA cardiac diagnostics",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://localhost:3001",
        "http://127.0.0.1:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Request / Response models ────────────────────────────────────────────────

class AnalyzeRequest(BaseModel):
    session_id: str = Field(..., min_length=1)
    experience_level: str = Field(default="seasoned")


class AnalyzeResponse(BaseModel):
    session_id: str
    status: str
    kra_raw: Optional[str] = None
    kra_result: Optional[dict[str, Any]] = None
    source: str = "huggingface_space"
    space_url: Optional[str] = None
    duration_ms: int = 0
    error: Optional[str] = None


def _normalize_symptoms_text(extraction: dict[str, Any]) -> str:
    symptoms_list = extraction.get("symptoms", []) or []
    risk_factors = extraction.get("risk_factors", []) or []
    translated_text = (extraction.get("translated_text") or "").strip()

    placeholder_prefixes = (
        "awaiting clinical input",
        "awaiting input",
        "no clinical input",
        "pending clinical input",
    )

    use_translated_text = bool(translated_text) and not translated_text.lower().startswith(placeholder_prefixes)

    symptoms_text = translated_text if use_translated_text else ", ".join(symptoms_list)
    if risk_factors:
        symptoms_text += f"\nRisk factors: {', '.join(risk_factors)}"
    return symptoms_text.strip()


# ── Endpoints ────────────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    space_url = os.getenv("KRA_SPACE_URL", "")
    return {
        "status": "ok",
        "mode": "huggingface_space",
        "space_url": space_url,
        "hf_token_set": bool(get_hf_token()),
    }


@app.post("/analyze", response_model=AnalyzeResponse)
async def analyze(req: AnalyzeRequest):
    """
    Run KRA analysis via Hugging Face Space.

    Flow:
      1. Read session data from shared workflow DB
      2. Extract symptoms, ECG, labs from stored step payloads
      3. Read FAISS retrieval context (already generated by local pipeline)
      4. Build prompt
      5. Send to HF Space
      6. Return parsed result
    """
    t0 = time.time()

    # 1. Fetch session
    session = get_session(req.session_id)
    if session is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Session {req.session_id} not found in workflow DB",
        )

    step_payloads = session.get("step_payloads", {})

    # 2. Extract data from step payloads
    extraction = step_payloads.get("extraction", {})
    ecg_data = step_payloads.get("ecg", {})
    lab_data = step_payloads.get("lab", {})

    # Build symptoms text
    symptoms_text = _normalize_symptoms_text(extraction)

    if not symptoms_text.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No symptoms data found in session. Complete NLP extraction first.",
        )

    # ECG and labs from stored payloads
    ecg_dict = ecg_data.get("result", {}) if ecg_data else {}
    labs_dict = lab_data.get("result", {}) if lab_data else {}

    # 3. Read FAISS context (already generated by local pipeline)
    context_text = get_retrieval_context(req.session_id)

    # 4. Build prompt
    prompt = build_kra_prompt(
        symptoms_text=symptoms_text,
        context_text=context_text,
        ecg_dict=ecg_dict,
        labs_dict=labs_dict,
    )

    logger.info(
        "HF analysis started for session %s (%d char prompt)",
        req.session_id, len(prompt),
    )

    # 5. Send to HF Space
    try:
        hf_result = await call_hf_space(prompt)
    except Exception as exc:
        elapsed = int((time.time() - t0) * 1000)
        logger.error("HF Space inference failed: %s", exc)
        return AnalyzeResponse(
            session_id=req.session_id,
            status="FAILED",
            error=str(exc),
            duration_ms=elapsed,
        )

    elapsed = int((time.time() - t0) * 1000)

    # 6. Return result
    kra_result = hf_result.get("kra_result")
    return AnalyzeResponse(
        session_id=req.session_id,
        status="COMPLETED" if kra_result else "PARTIAL",
        kra_raw=hf_result.get("raw_text"),
        kra_result=kra_result,
        source="huggingface_space",
        space_url=hf_result.get("space_url"),
        duration_ms=elapsed,
    )


@app.get("/session/{session_id}")
async def session_info(session_id: str):
    """Read-only view of session data for debugging."""
    session = get_session(session_id)
    if session is None:
        raise HTTPException(status_code=404, detail="Session not found")
    return session


if __name__ == "__main__":
    import uvicorn
    reload_enabled = os.getenv("HUGG_BACKEND_RELOAD", "false").lower() == "true"
    uvicorn.run("main:app", host="0.0.0.0", port=8090, reload=reload_enabled)
